
services:
  postgres:
    image: postgres:18rc1
    container_name: neotool-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-neotool}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-neotool}
      POSTGRES_DB: ${POSTGRES_DB:-neotool_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: neotool-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: apache/kafka:4.1.0
    container_name: neotool-kafka
    restart: unless-stopped
    environment:
      # Essential KRaft configuration
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      - NODE_ID=1
      - PROCESS_ROLES=broker,controller
      - CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - CONTROLLER_LISTENER_NAMES=CONTROLLER
      - INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Useful for development
      - AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :9092 | grep LISTEN || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  loki:
    image: grafana/loki:2.9.8
    container_name: neotool-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"

  alloy:
    image: grafana/alloy:latest
    container_name: neotool-alloy
    command: run --config.file=/etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/log:/var/log:ro
      - ../..:/workspace:ro
    ports:
      - "12345:12345"
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: neotool-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.5.0
    container_name: neotool-tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml:ro
    ports:
      - "3200:3200"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.105.0
    container_name: neotool-otel
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:11.1.4
    container_name: neotool-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  api:
    build:
      context: ../../service
      dockerfile: app/Dockerfile
    container_name: neotool-api
    env_file: ../../.env
    environment:
      MICRONAUT_ENVIRONMENTS: docker
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      KAFKA_BROKER: kafka:9092
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started
    ports:
      - "8080:8080"

  router:
    image: ghcr.io/apollographql/router:v2.7.0
    depends_on:
      - api
    ports:
      - "4000:4000"
    volumes:
      - ../supergraph/supergraph.graphql:/dist/supergraph.graphql:ro
    command: ["--supergraph", "/dist/supergraph.graphql", "--dev"]

  web:
    build:
      context: ../../web
      dockerfile: Dockerfile
    container_name: neotool-web
    env_file: ../../.env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
