name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test:unit --run

  build:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Build app
        run: pnpm build
      - name: Start app
        run: pnpm start -p 3000 &
      - name: Wait for app
        run: npx wait-on http://localhost:3000
      - name: Run E2E tests
        run: pnpm test:e2e
