// Optimized Material-UI imports for better tree-shaking
// This file centralizes MUI imports to prevent duplicate bundling

// Core Material-UI components
export { default as Box } from '@mui/material/Box';
export { default as Container } from '@mui/material/Container';
export { default as Typography } from '@mui/material/Typography';
export { default as Card } from '@mui/material/Card';
export { default as CardContent } from '@mui/material/CardContent';
export { default as CardActions } from '@mui/material/CardActions';
export { default as Button } from '@mui/material/Button';
export { default as IconButton } from '@mui/material/IconButton';
export { default as TextField } from '@mui/material/TextField';
export { default as InputLabel } from '@mui/material/InputLabel';
export { default as InputAdornment } from '@mui/material/InputAdornment';
export { default as Select } from '@mui/material/Select';
export { default as MenuItem } from '@mui/material/MenuItem';
export { default as FormControl } from '@mui/material/FormControl';
export { default as FormControlLabel } from '@mui/material/FormControlLabel';
export { default as FormLabel } from '@mui/material/FormLabel';
export { default as Checkbox } from '@mui/material/Checkbox';
export { default as Switch } from '@mui/material/Switch';
export { default as Radio } from '@mui/material/Radio';
export { default as RadioGroup } from '@mui/material/RadioGroup';
export { default as Chip } from '@mui/material/Chip';
export { default as Badge } from '@mui/material/Badge';
export { default as Avatar } from '@mui/material/Avatar';
export { default as Tooltip } from '@mui/material/Tooltip';
export { default as Dialog } from '@mui/material/Dialog';
export { default as DialogTitle } from '@mui/material/DialogTitle';
export { default as DialogContent } from '@mui/material/DialogContent';
export { default as DialogActions } from '@mui/material/DialogActions';
export { default as Snackbar } from '@mui/material/Snackbar';
export { default as Alert } from '@mui/material/Alert';
export { default as CircularProgress } from '@mui/material/CircularProgress';
export { default as LinearProgress } from '@mui/material/LinearProgress';
export { default as Skeleton } from '@mui/material/Skeleton';
export { default as Divider } from '@mui/material/Divider';
export { default as List } from '@mui/material/List';
export { default as ListItem } from '@mui/material/ListItem';
export { default as ListItemIcon } from '@mui/material/ListItemIcon';
export { default as ListItemText } from '@mui/material/ListItemText';
export { default as ListItemButton } from '@mui/material/ListItemButton';
export { default as Paper } from '@mui/material/Paper';
export { default as Stack } from '@mui/material/Stack';
export { default as Grid } from '@mui/material/Grid';
export { default as Table } from '@mui/material/Table';
export { default as TableBody } from '@mui/material/TableBody';
export { default as TableCell } from '@mui/material/TableCell';
export { default as TableContainer } from '@mui/material/TableContainer';
export { default as TableHead } from '@mui/material/TableHead';
export { default as TableRow } from '@mui/material/TableRow';
export { default as TablePagination } from '@mui/material/TablePagination';
export { default as Autocomplete } from '@mui/material/Autocomplete';
export { default as Tabs } from '@mui/material/Tabs';
export { default as Tab } from '@mui/material/Tab';
export { default as Accordion } from '@mui/material/Accordion';
export { default as AccordionSummary } from '@mui/material/AccordionSummary';
export { default as AccordionDetails } from '@mui/material/AccordionDetails';
export { default as Breadcrumbs } from '@mui/material/Breadcrumbs';
export { default as Link } from '@mui/material/Link';
export { default as Stepper } from '@mui/material/Stepper';
export { default as Step } from '@mui/material/Step';
export { default as StepLabel } from '@mui/material/StepLabel';
export { default as StepContent } from '@mui/material/StepContent';
export { default as AppBar } from '@mui/material/AppBar';
export { default as Toolbar } from '@mui/material/Toolbar';
export { default as Drawer } from '@mui/material/Drawer';
export { default as CssBaseline } from '@mui/material/CssBaseline';
export { ThemeProvider } from '@mui/material/styles';
export { useTheme } from '@mui/material/styles';
export { styled } from '@mui/material/styles';
export { createTheme } from '@mui/material/styles';

// Material-UI Icons (only commonly used ones)
export { default as SearchIcon } from '@mui/icons-material/Search';
export { default as AddIcon } from '@mui/icons-material/Add';
export { default as EditIcon } from '@mui/icons-material/Edit';
export { default as DeleteIcon } from '@mui/icons-material/Delete';
export { default as SaveIcon } from '@mui/icons-material/Save';
export { default as CancelIcon } from '@mui/icons-material/Cancel';
export { default as CloseIcon } from '@mui/icons-material/Close';
export { default as CheckIcon } from '@mui/icons-material/Check';
export { default as ArrowBackIcon } from '@mui/icons-material/ArrowBack';
export { default as ViewComfyIcon } from '@mui/icons-material/ViewComfy';
export { default as ViewListIconAlt } from '@mui/icons-material/ViewList';
export { default as OpenInNewIcon } from '@mui/icons-material/OpenInNew';
export { default as ContentCopyIcon } from '@mui/icons-material/ContentCopy';
export { default as ArrowForwardIcon } from '@mui/icons-material/ArrowForward';
export { default as ExpandMoreIcon } from '@mui/icons-material/ExpandMore';
export { default as ExpandLessIcon } from '@mui/icons-material/ExpandLess';
export { default as MenuIcon } from '@mui/icons-material/Menu';
export { default as MoreVertIcon } from '@mui/icons-material/MoreVert';
export { default as SettingsIcon } from '@mui/icons-material/Settings';
export { default as HomeIcon } from '@mui/icons-material/Home';
export { default as DashboardIcon } from '@mui/icons-material/Dashboard';
export { default as PersonIcon } from '@mui/icons-material/Person';
export { default as NotificationsIcon } from '@mui/icons-material/Notifications';
export { default as EmailIcon } from '@mui/icons-material/Email';
export { default as PhoneIcon } from '@mui/icons-material/Phone';
export { default as LocationOnIcon } from '@mui/icons-material/LocationOn';
export { default as CalendarTodayIcon } from '@mui/icons-material/CalendarToday';
export { default as AccessTimeIcon } from '@mui/icons-material/AccessTime';
export { default as InfoIcon } from '@mui/icons-material/Info';
export { default as WarningIcon } from '@mui/icons-material/Warning';
export { default as ErrorIcon } from '@mui/icons-material/Error';
export { default as CheckCircleIcon } from '@mui/icons-material/CheckCircle';
export { default as VisibilityIcon } from '@mui/icons-material/Visibility';
export { default as VisibilityOffIcon } from '@mui/icons-material/VisibilityOff';
export { default as FilterListIcon } from '@mui/icons-material/FilterList';
export { default as SortIcon } from '@mui/icons-material/Sort';
export { default as RefreshIcon } from '@mui/icons-material/Refresh';
export { default as DownloadIcon } from '@mui/icons-material/Download';
export { default as UploadIcon } from '@mui/icons-material/Upload';
export { default as PrintIcon } from '@mui/icons-material/Print';
export { default as ShareIcon } from '@mui/icons-material/Share';
export { default as FavoriteIcon } from '@mui/icons-material/Favorite';
export { default as FavoriteBorderIcon } from '@mui/icons-material/FavoriteBorder';
export { default as StarIcon } from '@mui/icons-material/Star';
export { default as StarBorderIcon } from '@mui/icons-material/StarBorder';
export { default as ThumbUpIcon } from '@mui/icons-material/ThumbUp';
export { default as ThumbDownIcon } from '@mui/icons-material/ThumbDown';
export { default as HelpIcon } from '@mui/icons-material/Help';
export { default as QuestionAnswerIcon } from '@mui/icons-material/QuestionAnswer';
export { default as DescriptionIcon } from '@mui/icons-material/Description';
export { default as CodeIcon } from '@mui/icons-material/Code';
export { default as BuildIcon } from '@mui/icons-material/Build';
export { default as SecurityIcon } from '@mui/icons-material/Security';
export { default as SpeedIcon } from '@mui/icons-material/Speed';
export { default as AccessibilityIcon } from '@mui/icons-material/Accessibility';
export { default as DesignServicesIcon } from '@mui/icons-material/DesignServices';
export { default as MenuBookIcon } from '@mui/icons-material/MenuBook';
export { default as TableChartIcon } from '@mui/icons-material/TableChart';
export { default as DataObjectIcon } from '@mui/icons-material/DataObject';
export { default as AccountTreeIcon } from '@mui/icons-material/AccountTree';
export { default as TimelineIcon } from '@mui/icons-material/Timeline';
export { default as PaletteIcon } from '@mui/icons-material/Palette';
export { default as PaletteRoundedIcon } from '@mui/icons-material/PaletteRounded';
export { default as BuildRoundedIcon } from '@mui/icons-material/BuildRounded';
export { default as SecurityRoundedIcon } from '@mui/icons-material/SecurityRounded';
export { default as SpeedRoundedIcon } from '@mui/icons-material/SpeedRounded';
export { default as AccessibilityRoundedIcon } from '@mui/icons-material/AccessibilityRounded';
export { default as CodeRoundedIcon } from '@mui/icons-material/CodeRounded';
export { default as DesignServicesRoundedIcon } from '@mui/icons-material/DesignServicesRounded';
export { default as MenuBookRoundedIcon } from '@mui/icons-material/MenuBookRounded';
export { default as TableChartRoundedIcon } from '@mui/icons-material/TableChartRounded';
export { default as DescriptionRoundedIcon } from '@mui/icons-material/DescriptionRounded';
export { default as DashboardRoundedIcon } from '@mui/icons-material/DashboardRounded';
export { default as DataObjectRoundedIcon } from '@mui/icons-material/DataObjectRounded';
export { default as AccountTreeRoundedIcon } from '@mui/icons-material/AccountTreeRounded';
export { default as TimelineRoundedIcon } from '@mui/icons-material/TimelineRounded';
export { default as CategoryIcon } from '@mui/icons-material/Category';
export { default as WidgetsIcon } from '@mui/icons-material/Widgets';
export { default as ExtensionIcon } from '@mui/icons-material/Extension';
export { default as ViewModuleIcon } from '@mui/icons-material/ViewModule';
export { default as ViewListIcon } from '@mui/icons-material/ViewList';

// Material-UI X components (only if needed)
export { DatePicker } from '@mui/x-date-pickers/DatePicker';
export { TimePicker } from '@mui/x-date-pickers/TimePicker';
export { DateTimePicker } from '@mui/x-date-pickers/DateTimePicker';
export { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
export { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
