package io.github.salomax.neotool.security.model.account

import io.github.salomax.neotool.common.entity.BaseEntity
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.persistence.Version
import java.time.Instant
import java.util.UUID
import org.hibernate.annotations.Generated
import org.hibernate.generator.EventType

/**
 * JPA entity for security.accounts.
 * Account is the primary ownership boundary for resources; users access resources via account membership.
 * Id is generated by the database (DEFAULT uuidv7()) and read back after insert.
 */
@Entity
@Table(name = "accounts", schema = "security")
open class AccountEntity(
    @Id
    @Generated(event = [EventType.INSERT])
    @Column(columnDefinition = "uuid", insertable = false, updatable = false)
    override val id: UUID? = null,
    @Column(name = "account_name", nullable = false)
    open var accountName: String,
    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false)
    open var accountType: AccountType,
    @Enumerated(EnumType.STRING)
    @Column(name = "account_status", nullable = false)
    open var accountStatus: AccountStatus = AccountStatus.ACTIVE,
    @Column(name = "owner_user_id", columnDefinition = "uuid")
    open var ownerUserId: UUID? = null,
    @Column(name = "deleted_at")
    open var deletedAt: Instant? = null,
    @Column(name = "created_at", nullable = false)
    open var createdAt: Instant = Instant.now(),
    @Column(name = "updated_at", nullable = false)
    open var updatedAt: Instant = Instant.now(),
    @Version
    open var version: Long = 0,
) : BaseEntity<UUID?>(id)
