package io.github.salomax.neotool.security.model.account

import io.github.salomax.neotool.common.entity.BaseEntity
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.persistence.Version
import java.time.Instant
import java.util.UUID
import org.hibernate.annotations.Generated
import org.hibernate.generator.EventType

/**
 * JPA entity for security.account_memberships.
 * Links users to accounts with roles; at most one ACTIVE default membership per user.
 * DB constraint chk_default_membership_active: is_default=true implies membership_status='ACTIVE'.
 * Id is generated by the database (DEFAULT uuidv7()) and read back after insert.
 */
@Entity
@Table(name = "account_memberships", schema = "security")
open class AccountMembershipEntity(
    @Id
    @Generated(event = [EventType.INSERT])
    @Column(columnDefinition = "uuid", insertable = false, updatable = false)
    override val id: UUID? = null,
    @Column(name = "account_id", nullable = false, columnDefinition = "uuid")
    open var accountId: UUID,
    @Column(name = "user_id", nullable = false, columnDefinition = "uuid")
    open var userId: UUID,
    @Enumerated(EnumType.STRING)
    @Column(name = "account_role", nullable = false)
    open var accountRole: AccountRole,
    @Enumerated(EnumType.STRING)
    @Column(name = "membership_status", nullable = false)
    open var membershipStatus: MembershipStatus = MembershipStatus.PENDING,
    @Column(name = "joined_at")
    open var joinedAt: Instant? = null,
    @Column(name = "is_default", nullable = false)
    open var isDefault: Boolean = false,
    @Column(name = "invited_by", columnDefinition = "uuid")
    open var invitedBy: UUID? = null,
    @Column(name = "invited_at")
    open var invitedAt: Instant? = null,
    @Column(name = "invitation_token")
    open var invitationToken: String? = null,
    @Column(name = "invitation_expires_at")
    open var invitationExpiresAt: Instant? = null,
    @Column(name = "removed_at")
    open var removedAt: Instant? = null,
    @Column(name = "removed_by", columnDefinition = "uuid")
    open var removedBy: UUID? = null,
    @Version
    open var version: Long = 0,
) : BaseEntity<UUID?>(id)
