
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/backend-deployment.yaml
  - ../../base/backend-service.yaml
  - ../../base/web-deployment.yaml
  - ../../base/web-service.yaml
