name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  unit:
    name: Typecheck, Lint & Vitest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Unit tests (Vitest)
        run: npm run test

  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    needs: unit
    timeout-minutes: 20
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright (browsers & deps)
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright)
        env:
          # nosso config .mjs já sobe o Next com NEXT_PUBLIC_MSW=1/NEXT_PUBLIC_E2E=1
          NODE_ENV: development
        run: npm run e2e

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web/playwright-report
          if-no-files-found: ignore
